DROP TABLE IF EXISTS sec_code;
CREATE TABLE sec_code (
	codeId_n INT UNSIGNED AUTO_INCREMENT NOT NULL,
	type_x VARCHAR(20) NOT NULL,
	name_x VARCHAR(50) NOT NULL,
	value_x VARCHAR(50) NOT NULL,
	desc_x VARCHAR(200) NULL,
	active_c CHAR(1) NOT NULL DEFAULT 'A',
	crtBy_m VARCHAR(20) NOT NULL DEFAULT 'System',
	crtOn_dt TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY (codeId_n)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;