DROP TABLE IF EXISTS SEC_user;
CREATE TABLE SEC_user (
	userId_n INT NOT NULL AUTO_INCREMENT,
	username_m VARCHAR(20) NOT NULL,
	password_x VARCHAR(64) NOT NULL,
	enabled_c CHAR NOT NULL DEFAULT 'Y',
	crtOn_dt DATETIME NOT NULL,
	crtBy_m VARCHAR(20) NOT NULL,
	updOn_dt TIMESTAMP NULL,
	updBy_m VARCHAR(20) NULL,
	PRIMARY KEY(userId_n)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS SEC_role;
CREATE TABLE SEC_role (
	roleId_n INT AUTO_INCREMENT NOT NULL,
	roleName_m VARCHAR(20) NOT NULL,
	enabled_c CHAR NOT NULL DEFAULT 'Y',
	crtOn_dt DATETIME NOT NULL,
	crtBy_m VARCHAR(20) NOT NULL,
	PRIMARY KEY(roleId_n)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS SEC_resource;
CREATE TABLE SEC_resource (
	resId_n INT AUTO_INCREMENT NOT NULL,
	resType_x VARCHAR(20) NOT NULL,
	resPath_x VARCHAR(20) NOT NULL,
	resDesc_x VARCHAR(50) NULL,
	enabled_c CHAR NOT NULL DEFAULT 'Y',
	crtOn_dt DATETIME NOT NULL,
	crtBy_m VARCHAR(20) NOT NULL,
	PRIMARY KEY(resId_n)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS SEC_user2role;
CREATE TABLE SEC_user2role (
	id_n INT AUTO_INCREMENT NOT NULL,
	userId_n INT NOT NULL,
	roleId_n INT NOT NULL,
	crtOn_dt DATETIME NOT NULL,
	crtBy_m VARCHAR(20) NOT NULL,
	PRIMARY KEY(id_n)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS SEC_role2res;
CREATE TABLE SEC_role2res (
	id_n INT AUTO_INCREMENT NOT NULL,
	roleId_n INT NOT NULL,
	resId_n INT NOT NULL,
	crtOn_dt DATETIME NOT NULL,
	crtBy_m VARCHAR(20) NOT NULL,
	PRIMARY KEY(id_n)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS SEC_loginHistory;
CREATE TABLE SEC_loginHistory (
	id_n INT AUTO_INCREMENT NOT NULL,
	username_m VARCHAR(20) NOT NULL,
	ip_x VARCHAR(20) NOT NULL,
	status_x VARCHAR(10) NOT NULL,
	crtOn_dt TIMESTAMP NOT NULL,
	PRIMARY KEY(id_n)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;